### ISSUE TITLE
Add icons for folder and files in list views

### ISSUE THREAD

**Issue by c-eg** [c-eg/ShowRenamer#59]

**Comment by tarunsamanta2k20** [comment]
I'D LIKE TO WOTK ON IT.

**Comment by c-eg** [comment]
> I'D LIKE TO WOTK ON IT.

Thank you! Please go ahead, I'll assign you to the issue :)

**Comment by tarunsamanta2k20** [comment]
@c-eg i am getting this error while running the application.

[ERROR] No plugin found for prefix 'javafx' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/tarun/.m2/repository), central (https://repo.maven.apache.org/maven2)]



Please suggest me how to fix it.

**Comment by c-eg** [comment]
Hi, I think this is a mistake I made when changing stuff in the Pom. To fix it, I think adding the "javafx-maven-plugin" to the build section of the Pom will fix it. Let me know if it works.

**Comment by tarunsamanta2k20** [comment]
> Hi, I think this is a mistake I made when changing stuff in the Pom. To fix it, I think adding the "javafx-maven-plugin" to the build section of the Pom will fix it. Let me know if it works, otherwise I can fix it a little later today.

@c-eg no, it won't. I have tried once.

**Comment by c-eg** [comment]
Did you make sure to use the main class as ShowRenamerLauncher?

**Comment by c-eg** [comment]
@tarunsamanta2k20 did you still plan on doing this? I'm happy to help with issues with setup :)

**Comment by tarunsamanta2k20** [comment]
@c-eg yes, probably I will update over here by EOD.

**Comment by tarunsamanta2k20** [comment]
@c-eh sorry I couldn't solve this issue.

**Comment by tarunsamanta2k20** [comment]
Apr 25, 2023 9:43:27 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @11614aef'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javafx.fxml.LoadException: 
file:/home/tarun/Desktop/ShowRenamer/target/show-renamer-0.8.0-ALPHA.jar!/view/rename.fxml:14

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3331)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3287)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3255)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3227)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3203)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3196)
	at uk.co.conoregan.showrenamer.ShowRenamerApplication.start(ShowRenamerApplication.java:61)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
	... 22 more
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Properties.load(Properties.java:407)
	at uk.co.conoregan.showrenamer.suggestion.TMDBSuggestionProvider.<init>(TMDBSuggestionProvider.java:61)
	at uk.co.conoregan.showrenamer.controller.RenameController.<init>(RenameController.java:59)
	... 28 more
tarun@tarun-HP-Notebook:~/Desktop/ShowRenamer/target$ java -jar original-show-renamer-0.8.0-ALPHA.jar
no main manifest attribute, in original-show-renamer-0.8.0-ALPHA.jar
tarun@tarun-HP-Notebook:~/Desktop/ShowRenamer/target$ java -jar show-renamer-0.8.0-ALPHA.jar
Apr 25, 2023 9:44:04 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @11614aef'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javafx.fxml.LoadException: 
file:/home/tarun/Desktop/ShowRenamer/target/show-renamer-0.8.0-ALPHA.jar!/view/rename.fxml:14

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2808)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3331)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3287)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3255)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3227)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3203)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3196)
	at uk.co.conoregan.showrenamer.ShowRenamerApplication.start(ShowRenamerApplication.java:61)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
	... 22 more
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Properties.load(Properties.java:407)
	at uk.co.conoregan.showrenamer.suggestion.TMDBSuggestionProvider.<init>(TMDBSuggestionProvider.java:61)
	at uk.co.conoregan.showrenamer.controller.RenameController.<init>(RenameController.java:59)
	... 28 more

**Comment by c-eg** [comment]
This is because you did not have an api_key.properties file in the correct location. Please see the readme.
